### ISSUE TITLE
Button does not playback the correct sentence

### ISSUE THREAD

**Issue by PotentialTumbleweed** [camiloaa/duolingotreeenhancer#14]
I am using Enchanced mode while studying Spanish from English. When there is a situation such as in the screenshot below, , two buttons appear as expected, but the second button does not read the sentence it is next to, but rather the one above it. In other words, both buttons read the first sentence. 

Please note, when the answer first appears, it is read correctly, but pressing the button only repeats the first sentence.

I hope this is something that can be fixed. Thanks.

![Screen Shot 2021-08-29 at 5 48 57 PM](https://user-images.githubusercontent.com/79097623/131267585-25b4b65e-a862-4c71-b3b4-543974ed2c47.png)

**Comment by camiloaa** [comment]
Thank you for your feedback. I'll work on it.

**Comment by PotentialTumbleweed** [comment]
Hello. I downloaded 1.4.3. and the problem still exists, and in addition now the buttons look different. Furthermore, clicking in the middle does not work, but instead one must click them near the bottom.

![Screen Shot 2021-09-01 at 12 21 06 AM](https://user-images.githubusercontent.com/79097623/131611387-f2321c2b-93e0-4389-85cf-cc699fd9b145.png)

**Comment by camiloaa** [comment]
Yes, that patch had nothing to do with your report. It was just a cosmetic patch because duolingo changed its CSS.

**Comment by PotentialTumbleweed** [comment]
Hello again. Pardon, but I regret to report that I am still facing the same problem even though you have closed this bug report. It is still not working for me, and I am still having the same problemñ just tried it again tonight. 😞

**Comment by PotentialTumbleweed** [comment]
I am still having the same problem, though.

**Comment by camiloaa** [comment]
@PotentialTumbleweed What version of the script are you using? I noticed last time it took a few days to update (version 1.4.3 came the say day you reported the bug, but it only got updated in your system two or three days later). 

What TTS are you using? I tested it only with google TTS, since my OS doesn't have a build-in TTS. That might also be a factor.
