### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by JumpRopeCanuck** [camiloaa/duolingotreeenhancer#7]
I don't know how hard you worked to make this script, but I just wanted to say thank you. I use a few more to make Duolingo more challenging, and everything seems to be working out. I'm really pleased with your script and the others I use. Thanks again!

**Comment by JumpRopeCanuck** [comment]
For "Write this in (non-English language)" questions, I can see the text again. What happens is the following, which I hope I added correctly.
![Screen Shot 2020-09-08 at 9 47 25 PM](https://user-images.githubusercontent.com/70121120/92544881-f4e6e480-f21c-11ea-8f08-d0a3e476acae.png)

**Comment by JumpRopeCanuck** [comment]
The issue also occurs with "Write this in English" questions with audio. 
![Screen Shot 2020-09-08 at 9 53 55 PM](https://user-images.githubusercontent.com/70121120/92545468-34620080-f21e-11ea-80d4-79182647d8ce.png)

**Comment by JumpRopeCanuck** [comment]
The issue also occurs with "Write this in English" questions with audio.
![Screen Shot 2020-09-08 at 9 58 29 PM](https://user-images.githubusercontent.com/70121120/92545572-725f2480-f21e-11ea-827b-57a01d3a0e0c.png)

**Comment by camiloaa** [comment]
Thanks for the report. I don't get many of those exercises. Should be fixed now. Please test and close the issue or add more information, depending on the result.

**Comment by JumpRopeCanuck** [comment]
See about making a re-write that will keep the text hidden when we hover the cursor over the speaker button (and click to replay the audio). In the second picture, the cursor was over the button, but for some reason it wasn’t captured in the screenshot.


Best regards! And keep up the good work.

**Comment by JumpRopeCanuck** [comment]
I would like to see all text hidden when it's accompanied by audio. Not just for non-English text accompanied by non-English audio, but also for "Write this in English" sentences, which show the target language, we'll hear the audio for it, and there may be tiles with the english words at the bottom, or we'll have to type the answer. Here's an example of this issue in Spanish-from-English:
![Screen Shot 2020-09-10 at 9 38 51 AM](https://user-images.githubusercontent.com/70121120/92737836-750a6880-f349-11ea-98bf-24f3dfec2d3a.png)
......I think the issue is that the text isn't hidden when there's a **new** word......

......Here's a "Write this in Spanish" sentence with no audio, English text, and the text is visible:
![Screen Shot 2020-09-10 at 9 52 43 AM](https://user-images.githubusercontent.com/70121120/92740087-776dc200-f34b-11ea-832f-f81b29bece90.png)
......As always, please take your time and keep up the good work......

**Comment by camiloaa** [comment]
Which version are you running?

**Comment by JumpRopeCanuck** [comment]
1.3.0-pre4

**Comment by camiloaa** [comment]
Update, as I said in my first answer, it should be fixed now (1.3.0-pre5)

**Comment by JumpRopeCanuck** [comment]
> On Sep 11, 2020, at 1:10 AM, Camilo Alejandro <notifications@github.com> wrote:
> 
Maybe you can help. Pictures still aren’t being hidden. I’m running version 1.3.0-pre5 of your script. I have the settings box at the top of the skill tree set to hide pictures. Is there any other info I could provide you?

**Comment by camiloaa** [comment]
That's not working yet. The whole thing got broken after the last update to duolingo, and I  haven't have time to fix it all. Besides, not all pictures get hidden, only pictures in exercises where you have to name something according to a picture. That's only useful if you are doing a reverse three (e.g. using English for Hungarian speakers to learn Hungarian).

**Comment by camiloaa** [comment]
One problem with duolingo is the huge number of different tests they run at any time and the many small differences between them. I tried to repeat the error you got in your last screenshot, and it works just fine. No idea how to proceed.

![imagen](https://user-images.githubusercontent.com/2361161/92991675-e7b04b00-f4e5-11ea-973f-4ed41f2fb9b1.png)

**Comment by JumpRopeCanuck** [comment]
I appreciate all your hard work. Apologies for sounding like I’m nagging. 


Regards,

Stephen

**Comment by camiloaa** [comment]
Not nagging at all. User's feedback is important to fix issues. In this case I don't want the script showing green where it shouldn't, and because I can't replicate the error, I literally don't know what to do now.
